### PR TITLE
Fix Rust 1.78 template woe

### LINKED ISSUE #8: spin-trigger-cron is not compiling with # rustc --version rustc 1.78.0-beta.1 (efd9d2df1 2024-03-18)
```
# cargo build --release
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/spin-91500438ac5656d2/22c2ac5/templates/http-rust/content/Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
error: invalid character `{` in package name: `{{project-name | kebab_case}}`, the first character must be a Unicode XID start character (most letters or `_`)
 --> ../../../.cargo/git/checkouts/spin-91500438ac5656d2/22c2ac5/templates/redis-rust/content/Cargo.toml:2:8
  |
2 | name = "{{project-name | kebab_case}}"
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
    Finished `release` profile [optimized] target(s) in 0.97s
```

rustc stable works fine which is rustc 1.76.0 (07dca489a 2024-02-04).
1.78 Will be stable on: 2 May, 2024. So it is more like FYI

### PR DESCRIPTION
**Pull request by itowlson**
Fixes #8

### CODE REVIEW

**Comment by itowlson** [comment]
Note this requires Spin 2.5 so we need to make sure we have template tags for Spin 2.3 and Spin 2.4 to not pick this up

**Review by fibonacci1729 — APPROVED** [review]

**Comment by itowlson** [comment]
Has someone set up a required check on `ubuntu-latest` but no build step that goes with it?

**Comment by itowlson** [comment]
@rajatjindal do you have powers to override or fix the stuck check?  Thanks!

**Comment by endocrimes** [comment]
Fixed

**Comment by itowlson** [comment]
Thank you @endocrimes!

**Comment by rajatjindal** [comment]
> @rajatjindal do you have powers to override or fix the stuck check? Thanks!

Hi Ivan, sorry I was OOO on Friday and do not have enough permissions anyways :).

**Pull request merged**
